### ISSUE TITLE
Feauture request - projects(groups)

### ISSUE THREAD

**Issue by schvabodka-man** [IonicaBizau/idea#10]
That's a nice app but i found one big problem for me - you can't sort ideas into kinda like groups or sort it by tags, and having separate group for different kinds of ideas. So that would be great if you can implement it.

**Comment by IonicaBizau** [comment]
Would be nice to have tags! I use this like a brainstorm store, but grouping by tags would be nice. Contributions are welcome! :+1:

**Comment by ghost** [comment]
Did you add tags?
